Orders from users to group
coopdevs/katuma-web pull request #30
Opened 2016-11-04 18:31 UTC by enricostano

```
TypeError: Cannot read property 'props' of null
Object.ReactElement.cloneElement
/home/ubuntu/katuma-web/node_modules/react/lib/ReactElement.js:277:34
Object.ReactElementValidator.cloneElement
/home/ubuntu/katuma-web/node_modules/react/lib/ReactElementValidator.js:218:48
Base.render
/home/ubuntu/katuma-web/src/containers/Group/Base.js:38:16
Base.tryRender
/home/ubuntu/katuma-web/node_modules/react-transform-catch-errors/lib/index.js:34:31
Base.tryRender
/home/ubuntu/katuma-web/node_modules/react-transform-catch-errors/lib/index.js:34:31
Base.tryRender
/home/ubuntu/katuma-web/node_modules/react-transform-catch-errors/lib/index.js:34:31
Base.tryRender
/home/ubuntu/katuma-web/node_modules/react-transform-catch-errors/lib/index.js:34:31
Base.tryRender [as render]
/home/ubuntu/katuma-web/node_modules/react-transform-catch-errors/lib/index.js:34:31
/home/ubuntu/katuma-web/node_modules/react/lib/ReactCompositeComponent.js:793:21
measureLifeCyclePerf
/home/ubuntu/katuma-web/node_modules/react/lib/ReactCompositeComponent.js:74:12
```
This is my screenshot for now :trollface:

2016-11-08 17:13 UTC, enricostano commented on src/containers/Group/Orders/index.js
> +const mapStateToProps = (_state) => {
```
[0] /home/ubuntu/katuma-web/src/containers/Group/Orders/index.js
[0]   57:26  error  "_state" is defined but never used  no-unused-vars
[0] 
[0] ✖ 1 problem (1 error, 0 warnings)
```
@andresgutgon @naoisegolden @edulan como quito eso, que quiere de mi?

2016-11-08 17:16 UTC, edulan commented on src/containers/Group/Orders/index.js
> +const mapStateToProps = (_state) => {
quiere tu :moneybag:

2016-11-08 17:17 UTC, edulan commented on src/containers/Group/Orders/index.js
> +const mapStateToProps = (_state) => {
http://eslint.org/docs/rules/no-unused-vars#varsignorepattern

2016-11-08 17:18 UTC, edulan commented on src/containers/Group/Orders/index.js
> +const mapStateToProps = (_state) => {
``` json
"no-unused-vars": ["error", { "varsIgnorePattern": "^_" }]
```

2016-11-09 10:02 UTC, enricostano commented on src/containers/Group/Orders/index.js
> +const mapStateToProps = (_state) => {
Pero cual es la diferencia con este https://github.com/coopdevs/katuma-web/blob/develop/src/containers/Group/Producers/List.js#L149

tampoco alli se usa `_state`, verdad?

2016-11-09 10:12 UTC, edulan commented on src/containers/Group/Orders/index.js
> +const mapStateToProps = (_state) => {
Tiene que ver con la opción "after-used" que viene por defecto:

> after-used - only the last argument must be used. This allows you, for instance, to have two named parameters to a function and as long as you use the second argument, ESLint will not warn you about the first. This is the default setting.

http://eslint.org/docs/rules/no-unused-vars#args

2016-11-29 11:21 UTC, sauloperez commented on src/containers/Group/Orders/CurrentOrder/AddProductsModal/index.js
> +          HOLA
:trollface:

2016-11-29 11:26 UTC, edulan commented on src/containers/Group/Orders/CurrentOrder/AddProductsModal/index.js
> +          HOLA
ke ase

2016-11-29 14:23 UTC, enricostano commented on src/containers/Group/Orders/Item/index.js
> +import { connect } from 'react-redux';
remove `connect`

2016-11-29 14:23 UTC, enricostano commented on src/containers/Group/Orders/List/index.js
> +import { connect } from 'react-redux';
remove `connect`

2016-11-29 14:24 UTC, enricostano commented on src/containers/Group/Orders/CurrentOrder/AddProductsModal/index.js
> +          HOLA
que pasa? no se puede ya ni ser educados y saludar?

2016-11-29 20:25 UTC, andresgutgon requested changes

2016-11-29 20:25 UTC, andresgutgon commented on package.json
> -    "postinstall": "webpack --display-error-details --config webpack/prod.config.js",
Why?

2016-11-29 20:25 UTC, andresgutgon commented on src/containers/Group/Orders/CurrentOrder/OrderLines/Base.js
> +export default OrderLinesBase;
This component is not necessary. It's doing nothing you could use directly 'Lis' component

2016-11-29 20:25 UTC, andresgutgon commented on src/containers/Group/Orders/CurrentOrder/index.js
> +  }
:fire:

2016-11-29 20:25 UTC, andresgutgon commented on src/containers/Group/Orders/CurrentOrder/index.js
> +import { load as load2 } from 'redux/modules/order_lines';
Better name please

2016-11-30 11:58 UTC, enricostano commented on package.json
> -    "postinstall": "webpack --display-error-details --config webpack/prod.config.js",
Because it's slow and we don't need it

2016-11-30 11:58 UTC, enricostano commented on src/containers/Group/Orders/CurrentOrder/OrderLines/Base.js
> +export default OrderLinesBase;
Yep, I know. I was just doing some experiment.

2016-12-04 15:34 UTC, andresgutgon approved these changes

2016-12-04 15:36 UTC, merged